import { locales } from "@/i18n/config";

const BASE_URL = "https://www.viziai.app";

/** Sitemap index linking to per-locale sitemaps generated by app/sitemap.ts */
export function GET() {
  const entries = locales
    .map(
      (locale) =>
        `  <sitemap>\n    <loc>${BASE_URL}/sitemap/${locale}.xml</loc>\n  </sitemap>`,
    )
    .join("\n");

  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${entries}
</sitemapindex>`;

  return new Response(xml, {
    headers: { "Content-Type": "application/xml" },
  });
}
